version: 2.1

parameters:
  test:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.1.0

executors:
  ios:
    macos:
      xcode: 15.0.1
    resource_class: macos.x86.medium.gen2
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    environment:
      FL_OUTPUT_DIR: output
      LANG: en_US.UTF-8

jobs:
  create_certs:
    executor: ios
    steps:
      - checkout

workflows:
  demo_text:
    when: << pipeline.parameters.test >>
    jobs:
      - create_certs:
          context:
            - expo
            - app_store
